# 基础镜像
FROM daba0007/python2.7

# 维护者信息
MAINTAINER daba0007

ADD dabaweb.tar.gz /usr/src/ 

# app 所在目录
WORKDIR /usr/src/dabaweb

# 安装 app 所需依赖
RUN pip install --no-cache-dir -r requirement.txt -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
